# -*- coding: utf-8 -*-
"""Main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Nx8cDsJ4gIV2te1Phm8MIPJ5PcexLJH
"""

from fastapi import FastAPI
from predictor.predictor_logic import router as predictor_router
from bot.bot_logic import router as bot_router

app = FastAPI()

# Dono ko "include" kar lo
app.include_router(predictor_router, prefix="/predict")
app.include_router(bot_router, prefix="/bot")
@app.api_route("/", methods=["GET", "HEAD"])
async def health_check():
    return {"status": "online"}
