# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vggiTvqLdyj9uuXCHiFq49mWZ7UVoQMY
"""

import pandas as pd
import numpy as np
url = "https://raw.githubusercontent.com/omprakashpatna18-del/Capstone-Project/main/Exam_Score_Prediction.csv"

data = pd.read_csv(url)
print(data.head())



import uvicorn
import joblib

import google.genai as genai

from fastapi import FastAPI
from fastapi import APIROUTER

from pydantic import BaseModel







model = joblib.load("xgb_model.joblib")
class StudentData(BaseModel):
    age: int
    gender: str
    course: str
    study_hours: float
    class_attendance: float
    internet_access: str
    sleep_hours: float
    sleep_quality: str
    study_method: str
    facility_rating: str
    exam_difficulty: str

FEATURE_COLUMNS = [
      'age', 'gender', 'course', 'study_hours', 'class_attendance',
          'internet_access', 'sleep_hours', 'sleep_quality',
              'study_method', 'facility_rating', 'exam_difficulty'
]

master_map= {
      'gender': {'male': 0, 'female': 1, 'other': 2},
      'course': {'b.tech': 2, 'bca': 5, 'b.sc': 1, 'bba': 4, 'diploma': 6,'b.com':0,'ba':3},
      'internet_access': {'yes': 1, 'no': 0},
      'sleep_quality': {'poor': 2, 'average': 0, 'good': 1},
      'study_method': {'self-study':4,'group study':1,'coaching':0,'online videos':3,'mixed':2},
      'facility_rating': {'low': 1, 'medium': 0, 'high': 2},
      'exam_difficulty': {'easy': 0, 'moderate': 2, 'hard': 1},
                              }
import os
import google.genai as genai
gemini_model=genai.Client(api_key=os.environ.get('GEMINI_API_KEY'))

def helper(data):
    """
    Takes raw input from HTML form, encodes it exactly
    like your notebook, and returns XGBoost prediction.
    """

    # Build raw input dict (student_id excluded)
    raw = {
        'age'             : int(data.get('age', 20)),
        'gender'          : str(data.get('gender', 'male')).lower().strip(),
        'course'          : str(data.get('course', 'b.tech')).lower().strip(),
        'study_hours'     : float(data.get('study_hours', 5)),
        'class_attendance': float(data.get('class_attendance', 75)),
        'internet_access' : str(data.get('internet_access', 'yes')).lower().strip(),
        'sleep_hours'     : float(data.get('sleep_hours', 7)),
        'sleep_quality'   : str(data.get('sleep_quality', 'average')).lower().strip(),
        'study_method'    : str(data.get('study_method', 'mixed')).lower().strip(),
        'facility_rating' : str(data.get('facility_rating', 'medium')).lower().strip(),
        'exam_difficulty' : str(data.get('exam_difficulty', 'moderate')).lower().strip(),
    }

    df = pd.DataFrame([raw], columns=FEATURE_COLUMNS)
 
    # Apply same encoding as your notebook
    for col, mapping in master_map.items():
        if col in df.columns:
            val = str(df[col].iloc[0]).lower().strip()
            df[col] = mapping.get(val, 0)

    # Convert all to correct dtypes
    df= df.astype({
        'age'             : 'int64',
        'gender'          : 'int64',
        'course'          : 'int64',
        'study_hours'     : 'float64',
        'class_attendance': 'float64',
        'internet_access' : 'int64',
        'sleep_hours'     : 'float64',
        'sleep_quality'   : 'int64',
        'study_method'    : 'int64',
        'facility_rating' : 'int64',
        'exam_difficulty' : 'int64',
    })
    return df

def predict_marks(df):
    prediction = model.predict(df)[0]
    predicted_marks = round(float(prediction), 2)


    return predicted_marks

def features_ranked(df):

    # Feature importance (same as your notebook)
    importances = model.feature_importances_
    all_features_ranked = sorted(
        zip(importances, FEATURE_COLUMNS), reverse=True
    )

    return all_features_ranked


#app = FastAPI(title="Student Marks Predictor")

# CORS — HTML pages ko allow karo
#app.add_middleware(
#CORSMiddleware,
#allow_origins=["*"],
#allow_methods=["*"],
#allow_headers=["*"],
                )

router=APIROUTER(
@router.post("/predict")
def suggest(data: dict):
    if "student_data" in data:
        student = data["student_data"]
    else:
        student = data
    processed_df = helper(student)
    marks = predict_marks(processed_df)
    features=features_ranked(processed_df)

    features_summary="\n".join(
        [f"{name}: {val:.4f}" for val, name in features]
    )

    prompt = f"""You are a helpful academic mentor. A student has received a predicted score of {marks}/100.

Student Profile:
- Age: {student['age']}
- Gender: {student['gender']}
- Course: {student['course']}
- Study Hours per day: {student['study_hours']}
- Class Attendance: {student['class_attendance']}%
- Internet Access: {student['internet_access']}
- Sleep Hours: {student['sleep_hours']}
- Sleep Quality: {student['sleep_quality']}
- Study Method: {student['study_method']}
- Facility Rating: {student['facility_rating']}
- Exam Difficulty: {student['exam_difficulty']}

Impact Factors:
{features_summary}

Task: Give a proper feedback to student in English. Keep it precise and straight to the point. Give suggestions to improve their marks. Do not hallucinate and predict marks.
Do not encourage the student to study for very long or short hours. Do not advise him/her to sleep too much or too little.
If you find the predicted marks more than 100 or class attendance more than 100, declare the data as invalid and tell the user to enter correct details.
Follow the given format:
1. Strengths
2. Areas to be Improved
3. Precautions
4. Suggestions
5. Overall Feedback
"""
    try:
        response = gemini_model.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )
        suggestions = response.text # Fixed: Removed the extra 't'

    except Exception as e:
        print("Gemini error:", e)
        # Fallback suggestions
        suggestions = """1. Strengths: Potential identified.
2. Areas to be Improved: Focus on weak spots.
3. Precautions: Maintain consistency.
4. Suggestions: Balance study and rest.
5. Overall Feedback: Good effort!"""

    # 5. Final Return (Aligned at 4 spaces)
    return {
        "predicted_marks": marks,
        "suggestions": suggestions
    }


